### ISSUE TITLE
undefined method `+' for :read:Symbol (NoMethodError)

### ISSUE THREAD

**Issue by MatUrbanski** [digitalocean/kartograph#18]
Hi, I was trying to use kartograph a little bit, here is my code:

```
require 'kartograph'

class User
  attr_accessor :name, :email, :id

  def initialize(name:'name', email:'email', id:'id')
    @name = name
    @email = email
    @id = id
  end

end

class UserMapping
  include Kartograph::DSL

  kartograph do
    mapping User # The object we're mapping

    property :name, :email, scopes: [:create, :update]
    property :id, scopes: :read
  end
end

user = User.new(name: 'Bobby Tables')
json_for_create = UserMapping.representation_for(:create, user)
```

it returns following error:

```
/home/mateusz/.rvm/gems/ruby-2.3.0/gems/kartograph-0.2.4/lib/kartograph/map.rb:14:in `property': undefined method `+' for :read:Symbol (NoMethodError)
  from /home/mateusz/kartograph_testing.rb:14:in `block in <class:UserMapping>'
  from /home/mateusz/.rvm/gems/ruby-2.3.0/gems/kartograph-0.2.4/lib/kartograph/dsl.rb:12:in `instance_eval'
  from /home/mateusz/.rvm/gems/ruby-2.3.0/gems/kartograph-0.2.4/lib/kartograph/dsl.rb:12:in `kartograph'
  from /home/mateusz/kartograph_testing.rb:10:in `<class:UserMapping>'
  from /home/mateusz/kartograph_testing.rb:7:in `<main>'
```

**Comment by MatUrbanski** [comment]
When I change scopes to accept array it works properly:

```
property :id, scopes: [:read]
```
